baseURL = "https://vibrant-borg-9cc729.netlify.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en-US"
metaDataFormat = "yaml"
paginate = 25
theme = "aether"

[outputs]
home = ["HTML", "RSS","JSON"]

[params]
brand = "Health IT Briefing"
description = "Netspective Media Health IT Briefing"

 